version: '3'

services:
  python-notebook:
    image: python-notebook:v1
    build:
      context: .
    volumes:
      - ../Ejecutables:/home/jovyan/work # Se deben agregar los archivos .properties a esta carpeta
    ports:
      - "8888:8888"
    command: jupyter nbconvert --to script --execute --ExecutePreprocessor.timeout=-1 Clasificador.ipynb && python Clasificador.py
